const collectionsdata = {
    toppicks: [
        {
            id: 1,
            title: "Women Composite Tassel Bag",
            image: "images/pick1.png",
            price: 25.00,
            button: "buy now",
        },
        {
            id: 2,
            title: "Chunky Heels Short Martin Boots",
            image: "images/pick2.png",
            price: 25.00,
            button: "buy now",
        },
        {
            id: 3,
            title: "Georgette Art Silk Saree",
            image: "images/pick3.png",
            price: 25.00,
            button: "buy now",
        },
        {
            id: 4,
            title: "Plain Rayon Front Slitted Kurta",
            image: "images/pick4.png",
            price: 25.00,
            button: "buy now",
        },
    ],

    productlists: [
        {
            id: 1,
            shortTitle: "ROTITA Cutout Neck...",
            title: "ROTITA Cutout Neck Pierced Sleeve Top",
            price: "899",
            image: "images/tops/top1.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.4,
            review: "(based on 2,320 reviews))",
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false }
            ],
            description: "Chic and elegant ROTITA Cutout Neck Pierced Sleeve Top, perfect for casual and semi-formal occasions.",
            details: [
                "Pack of : 1",
                "Color : Yellow",
                "Fabric : Polyester Blend",
                "Fabric Care : Hand wash or machine wash on gentle cycle",
                "Neckline : Cutout Neck",
                "Sleeve Style : Pierced, Long Sleeves",
            ]
        },
        {
            id: 2,
            shortTitle: "Polka Dot Lantern...",
            title: "Polka Dot Lantern Sleeve Tie Top",
            price: "999",
            image: "images/tops/top2.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.5,
            review: "(based on 1,050 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true }
            ],
            description: "Stylish Polka Dot Lantern Sleeve Tie Top for a trendy, playful look.",
            details: [
                "Pack of : 1",
                "Color : Red with White Polka Dots",
                "Fabric : Cotton Blend",
                "Fabric Care : Machine wash cold, do not bleach",
                "Neckline : V-neck",
                "Sleeve Style : Lantern Sleeves with Tie Detail",
            ]
        },
        {
            id: 3,
            shortTitle: "SHEIN Lantern Sleeve...",
            title: "SHEIN Lantern Sleeve Solid Peplum",
            price: "1,099",
            image: "images/tops/top3.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.3,
            review: "(based on 1,230 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true }
            ],
            description: "Elegant SHEIN Lantern Sleeve Solid Peplum top for a flattering, feminine silhouette.",
            details: [
                "Pack of : 1",
                "Color : Tiffany",
                "Fabric : Polyester",
                "Fabric Care : Hand wash cold, do not bleach",
                "Neckline : Round Neck",
                "Sleeve Style : Lantern Sleeves",
            ]
        },
        {
            id: 4,
            shortTitle: "Cindee Collared Blouse...",
            title: "Cindee Collared Blouse (Teal Green)",
            price: "799",
            image: "images/tops/top4.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.1,
            review: "(based on 850 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false }
            ],
            description: "Stylish Cindee Collared Blouse in Teal Green, perfect for both office wear and casual outings.",
            details: [
                "Pack of : 1",
                "Color : Teal Green",
                "Fabric : Polyester",
                "Fabric Care : Machine wash cold, tumble dry low",
                "Neckline : Collared",
                "Sleeve Style : Long Sleeves",
            ]
        },
        {
            id: 5,
            shortTitle: "Ralph Lauren Collection...",
            title: "Ralph Lauren Collection Striped Cotton Shirt",
            price: "1,599",
            image: "images/tops/shirt2.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.6,
            review: "(based on 540 reviews)",
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": false }
            ],
            description: "Timeless Ralph Lauren Collection Striped Cotton Shirt, combining sophistication and comfort for a polished look.",
            details: [
                "Pack of : 1",
                "Color : White and Blue Stripes",
                "Fabric : 100% Cotton",
                "Fabric Care : Dry clean or machine wash cold, do not bleach",
                "Neckline : Collared",
                "Sleeve Style : Full Sleeves",
            ]
        },
        {
            id: 6,
            shortTitle: "SHEIN EZwear Solid...",
            title: "SHEIN EZwear Solid Baggy Jeans",
            price: "1,299",
            image: "images/tops/jeans1.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.5,
            review: "(Based on 1200+ reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": false }
            ],
            description: "Stylish and comfortable baggy jeans with a solid design, perfect for a casual chic look.",
            details: [
                "Pack of : 1",
                "Color : Light Blue",
                "Fabric : Denim",
                "Fabric Care :  Machine Wash Cold, Do Not Bleach",
                "Fit : Baggy",
                "Closure : Button and Zipper",
                "Ideal For : Women",
                "Length : Full - Length"
            ]
        },
        {
            id: 7,
            shortTitle: "Medium Washed Flap...",
            title: "Medium Washed Flap Pocket Jeans",
            price: "1,499",
            image: "images/tops/jeans2.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.3,
            review: "(based on 1,120 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": false }
            ],
            description: "Trendy Medium Washed Flap Pocket Jeans with a casual yet stylish vibe, perfect for everyday wear.",
            details: [
                "Pack of : 1",
                "Color : Medium Blue Wash",
                "Fabric : Denim(98 % Cotton, 2 % Elastane)",
                "Fabric Care : Machine wash cold, tumble dry low",
                "Features : Flap Pockets, Button and Zip Closure, Belt Loops",
            ]
        },
        {
            id: 8,
            shortTitle: "Geometric Print Shirt...",
            title: "Geometric Print Shirt",
            price: "1,299",
            image: "images/tops/shirt1.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.5,
            review: "(based on 670 reviews)",
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false }
            ],
            description: "Stylish Geometric Print Shirt with vibrant patterns, perfect for making a bold fashion statement.",
            details: [
                "Pack of : 1",
                "Color : Black",
                "Fabric : 100 % Viscose",
                "Fabric Care : Machine wash cold, gentle cycle, iron on low heat",
                "Neckline : Collared",
                "Sleeve Style : Full Sleeves",
            ]
        },
        {
            id: 9,
            shortTitle: "SHEIN Pearl Embellished...",
            title: "SHEIN Pearl Embellished Peplum",
            price: "1,199",
            image: "images/tops/top5.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.4,
            review: "(based on 920 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": false }
            ],
            description: "Elegant SHEIN Pearl Embellished Peplum top, adding a touch of glamour to any outfit.",
            details: [
                "Pack of : 1",
                "Color : Yellow",
                "Fabric : Polyester Blend",
                "Fabric Care : Hand wash recommended, do not bleach",
                "Neckline : Round Neck",
                "Sleeve Style : Long Sleeves with Pearl Embellishments",
                "Features : Peplum Design, Pearl Detailing",
            ]
        },
        {
            id: 10,
            shortTitle: "stylish red top...",
            title: "stylish red top",
            price: "999",
            image: "images/tops/top6.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.3,
            review: "(based on 1,150 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true }
            ],
            description: "Chic and trendy stylish red top, perfect for elevating your casual or party look effortlessly.",
            details: [
                "Pack of : 1",
                "Color : Red",
                "Fabric : Polyester Blend",
                "Fabric Care : Machine wash cold, tumble dry low, iron on low heat",
                "Neckline : rounded",
                "Sleeve Style : full Sleeves",
                "Features : Fitted Design, Ruffled Hem",
            ]
        },
        {
            id: 11,
            shortTitle: "SHEIN Faux Pearl...",
            title: "SHEIN Faux Pearl Beaded Puff Sleeve Top",
            price: "1,399",
            image: "images/tops/top7.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.5,
            review: "(based on 860 reviews)",
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": true },
                { "label": "L", "available": false },
                { "label": "XS", "available": false },
                { "label": "XL", "available": true }
            ],
            description: "Elegant SHEIN Faux Pearl Beaded Puff Sleeve Top, combining sophistication and style for a refined look.",
            details: [
                "Pack of : 1",
                "Color : Maroon",
                "Fabric : Polyester",
                "Fabric Care : Hand wash recommended, do not bleach, line dry",
                "Neckline : Round Neck",
                "Sleeve Style : Puff Sleeves with Faux Pearl Beading",
                "Features : Pearl Detailing, Relaxed Fit",
            ]
        },
        {
            id: 12,
            shortTitle: "Mock Neck Red...",
            title: "Mock Neck Red Belted Long Sleeve",
            price: "1,599",
            image: "images/tops/top8.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.4,
            review: "(based on 940 reviews)",
            sizes: [
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": true }
            ],
            description: "Sophisticated Mock Neck Red Belted Long Sleeve top, perfect for formal and chic casual occasions.",
            details: [
                "Pack of : 1",
                "Color : Red",
                "Fabric : Polyester Blend",
                "Fabric Care : Machine wash cold, gentle cycle, do not bleach",
                "Neckline : Mock Neck",
                "Sleeve Style : Long Sleeves",
                "Features : Waist Belt for a Flattering Fit, Button Closure at Back",
            ]
        },
        {
            id: 13,
            shortTitle: "SHEIN Self-Tie...",
            title: "SHEIN Self-Tie Belted High-Low Top",
            price: "1,299",
            image: "images/tops/top9.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Tops",
            rating: 4.5,
            review: "(based on 1,020 reviews)",
            sizes: [
                { "label": "M", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false },
                { "label": "XXXL", "available": false }
            ],
            description: "Trendy SHEIN Self-Tie Belted High-Low Top, designed for a stylish and versatile look.",
            details: [
                "Pack of : 1",
                "Color : Dusty Rose",
                "Fabric : Polyester",
                "Fabric Care : Hand wash or machine wash cold, line dry, do not bleach",
                "Neckline : Rounded",
                "Sleeve Style : Long Sleeves with Cuffs",
                "Features : High - Low Hemline, Adjustable Self- Tie Belt",
            ]
        },
        {
            id: 14,
            shortTitle: "Plus Letter Graphic...",
            title: "Plus Letter Graphic Shirt Dress",
            price: "1,099",
            image: "images/tops/shirt3.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.3,
            review: "(based on 750 reviews)",
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": false },
                { "label": "L", "available": true },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": true },
                { "label": "3XL", "available": true }
            ],
            description: "Stylish Plus Letter Graphic Shirt Dress, offering comfort and casual flair for everyday wear.",
            details: [
                "Pack of : 1",
                "Color : Black with White Letter Print",
                "Fabric : Cotton Blend",
                "Fabric Care : Machine wash cold, gentle cycle, iron on low, do not bleach",
                "Neckline : Shirt Collar",
                "Sleeve Style : Long Sleeves with Buttoned Cuffs",
                "Features : Button - Down Front, Relaxed Fit, Graphic Letter Print",
            ]
        },
        {
            id: 15,
            shortTitle: "Kate Shirt Lapis...",
            title: "Kate Shirt Lapis",
            price: "2,199",
            image: "images/tops/shirt4.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.6,
            review: "(based on 560 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true }
            ],
            description: "Elegant Kate Shirt in Lapis, perfect for both formal and casual ensembles.",
            details: [
                "Pack of : 1",
                "Color : Lapis Blue",
                "Fabric : 100 % Cotton",
                "Fabric Care : Machine wash cold with similar colors, tumble dry low, iron on medium heat",
                "Neckline : Classic Shirt Collar",
                "Sleeve Style : Full Sleeves with Buttoned Cuffs",
                "Features : Tailored Fit, Front Button Closure, Lightweight and Breathable",
            ]
        },
        {
            id: 16,
            shortTitle: "silk shirt...",
            title: "silk shirt",
            price: "3,499",
            image: "images/tops/shirt5.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.8,
            review: "(based on 840 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XXL", "available": true }
            ],
            description: "Luxurious Silk Shirt in Maroon, exuding elegance and sophistication for any occasion.",
            details: [
                "Pack of : 1",
                "Color : Maroon",
                "Fabric : 100 % Pure Silk",
                "Fabric Care : Dry clean only, avoid direct sunlight to preserve color",
                "Neckline : Classic Shirt Collar",
                "Sleeve Style : Long Sleeves with Buttoned Cuffs",
                "Features : Smooth and Shiny Finish, Relaxed Fit, Button- Down Front",
            ]
        },
        {
            id: 17,
            shortTitle: "Tommy Hilfiger...",
            title: "Tommy Hilfiger Women's Cotton Printed Roll-Tab Utility Shirt",
            price: "999",
            image: "images/tops/shirt6.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.4,
            review: "(based on 1,200 reviews)",
            sizes: [
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XXL", "available": true }
            ],
            description: "Stylish and functional Tommy Hilfiger Women's Cotton Printed Roll-Tab Utility Shirt, designed for versatile everyday wear.",
            details: [
                "Pack of : 1",
                "Color : White with Navy Blue Printed Pattern",
                "Fabric : 100 % Cotton",
                "Fabric Care : Machine wash warm, tumble dry low, iron on medium heat if needed",
                "Neckline : Point Collar",
                "Sleeve Style : Long Sleeves with Roll - Tab Option",
                "Features : Utility Design with Chest Pockets, Button- Up Closure, Lightweight and Breathable",
            ]
        },
        {
            id: 18,
            shortTitle: "Glamorous oversized shirt...",
            title: "Glamorous oversized shirt in tonal tiger print-White",
            price: "1,299",
            image: "images/tops/shirt7.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.5,
            review: "(based on 870 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": false },
            ],
            description: "Bold and trendy Glamorous Oversized Shirt in Tonal Tiger Print, perfect for making a statement.",
            details: [
                "Pack of : 1",
                "Color : White with Tonal Tiger Print",
                "Fabric : 100 % Polyester",
                "Fabric Care : Machine wash cold, gentle cycle, do not bleach, tumble dry low",
                "Neckline : Classic Collar",
                "Sleeve Style : Long Sleeves with Buttoned Cuffs",
                "Features : Oversized Fit, Button- Up Front, Lightweight Fabric, Striking Animal Print",
            ]
        },
        {
            id: 19,
            shortTitle: "Women's Classic Striped...",
            title: "Women's Classic Striped Button Down Satin Shirt",
            price: "1,099",
            image: "images/tops/shirt8.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.6,
            review: "(based on 940 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false },
            ],
            description: "Sophisticated Women's Classic Striped Button-Down Satin Shirt, combining elegance and comfort for any occasion.",
            details: [
                "Pack of : 1",
                "Color : White with Black Stripes",
                "Fabric : Premium Satin",
                "Fabric Care : Hand wash cold, do not bleach, hang to dry, cool iron if necessary",
                "Neckline : Classic Shirt Collar",
                "Sleeve Style : Long Sleeves with Buttoned Cuffs",
                "Features : Smooth and Shiny Finish, Relaxed Fit, Full Button Closure, Timeless Striped Design",
            ]
        },
        {
            id: 20,
            shortTitle: "Zebra Striped Lantern...",
            title: "Zebra Striped Lantern Sleeve",
            price: "1,999",
            image: "images/tops/shirt9.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.4,
            review: "(based on 780 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false },
            ],
            description: "Chic Zebra Striped Lantern Sleeve Top, perfect for adding bold patterns to your wardrobe.",
            details: [
                "Pack of : 1",
                "Color : Black and White Zebra Stripes",
                "Fabric : Polyester Blend",
                "Fabric Care : Machine wash cold, do not bleach, tumble dry low, cool iron if needed",
                "Sleeve Style : Lantern Sleeves",
                "Features : Bold Zebra Print, Relaxed Fit, Lightweight and Comfortable",
            ]
        },
        {
            id: 21,
            shortTitle: "workwear shirt...",
            title: "workwear shirt",
            price: "2,499",
            image: "images/tops/shirt10.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Shirts",
            rating: 4.5,
            review: "(based on 1,200 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false },
            ],
            description: "Sleek and professional Workwear Shirt, ideal for office and formal settings.",
            details: [
                "Pack of : 1",
                "Color : Classic Pink",
                "Fabric : Cotton Blend",
                "Fabric Care : Machine wash warm, do not bleach, tumble dry low, warm iron if needed",
                "Neckline : Spread Collar",
                "Sleeve Style : Long Sleeves with Buttoned Cuffs",
                "Features : Slim Fit, Button- Up Front, Crisp and Breathable Fabric",
            ]
        },
        {
            id: 22,
            shortTitle: "High Waist Straight...",
            title: "High Waist Straight Jeans",
            price: "2,050",
            image: "images/tops/jeans3.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.7,
            review: "(based on 1,050 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false },
            ],
            description: "Trendy High Waist Straight Jeans, offering a flattering silhouette and versatile style for everyday wear.",
            details: [
                "Pack of : 1",
                "Color : Dark Blue",
                "Fabric : Denim (Cotton Blend)",
                "Fabric Care : Machine wash cold, do not bleach, tumble dry low, iron on low heat",
                "Fit : High-Waist, Straight Leg",
                "Closure : Zipper with Button Closure",
                "Features : Classic Five-Pocket Design, Clean Look, Comfortable Stretch",
            ]
        },
        {
            id: 23,
            shortTitle: "High Waist Raw...",
            title: "High Waist Raw Hem Wide Leg Jeans",
            price: "2,499",
            image: "images/tops/jeans4.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.6,
            review: "(based on 980 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true }
            ],
            description: "Stylish High Waist Raw Hem Wide Leg Jeans, combining comfort and fashion with a trendy, relaxed fit.",
            details: [
                "Pack of : 1",
                "Color : Light Wash Blue",
                "Fabric : Denim(Cotton Blend)",
                "Fabric Care : Machine wash cold, do not bleach, tumble dry low, iron on low heat",
                "Fit : High - Waist, Wide Leg, Raw Hem",
                "Closure : Button and Zipper Closure",
                "Features : Five - Pocket Style, Distressed Raw Hem, Comfortable Stretch",
            ]
        },
        {
            id: 24,
            shortTitle: "High Waist Button...",
            title: "High Waist Button Side Wide Leg Jeans",
            price: "2,799",
            image: "images/tops/jeans5.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.8,
            review: "(based on 1,150 reviews)",
            sizes: [
                { "label": "XS", "available": false },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": true },
                { "label": "3XL", "available": true }
            ],
            description: "Chic High Waist Button Side Wide Leg Jeans, offering a fashionable look with button detailing on the sides for added flair.",
            details: [
                "Pack of : 1",
                "Color : Black",
                "Fabric : Denim(Cotton Blend)",
                "Fabric Care : Machine wash cold, do not bleach, tumble dry low, iron on low heat",
                "Fit : High - Waist, Wide Leg",
                "Closure : Button Side Details, Zipper and Button Closure",
                "Features : Side Button Design, Five- Pocket Style, Relaxed and Comfortable Fit",
            ]
        },
        {
            id: 25,
            shortTitle: "High Waist Letter...",
            title: "High Waist Letter Graphic Slant Pocket Ripped Jeans",
            price: "1,350",
            image: "images/tops/jeans6.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.7,
            review: "(based on 1,200 reviews)",
            sizes: [
                { "label": "L", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false },
                { "label": "XXXL", "available": false }
            ],
            description: "Trendy High Waist Letter Graphic Slant Pocket Ripped Jeans, featuring stylish letter graphics and edgy ripped detailing for a bold, casual look.",
            details: [
                "Pack of : 1",
                "Color : Medium Wash Blue",
                "Fabric : Denim(Cotton Blend)",
                "Fabric Care : Machine wash cold, do not bleach, tumble dry low, iron on low heat",
                "Fit : High - Waist, Slim Fit",
                "Closure : Zipper and Button Closure",
                "Features : Ripped Distressed Design, Slant Pockets, Letter Graphic on Waistband",
            ]
        },
        {
            id: 26,
            shortTitle: "High Waist Contrast...",
            title: "High Waist Contrast Stitch Flare Leg Jeans",
            price: "1,799",
            image: "images/tops/jeans7.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.6,
            review: "(based on 1,150 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true }
            ],
            description: "High Waist Contrast Stitch Flare Leg Jeans with stylish contrast stitching for a vintage flair.",
            details: [
                "Color : Dark Wash Blue",
                "Fabric : Denim(Cotton Blend)",
                "Fit : High - Waist, Flare Leg",
                "Closure : Zipper and Button",
                "Features : Contrast Stitching, Flared Hem",
            ]
        },
        {
            id: 27,
            shortTitle: "High Waist Palazzo...",
            title: "High Waist Palazzo Jeans",
            price: "1,199",
            image: "images/tops/jeans8.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.7,
            review: "(based on 1,080 reviews))",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true },
                { "label": "XL", "available": true }
            ],
            description: "Elegant High Waist Palazzo Jeans with a loose, wide-leg fit for a comfortable and stylish look.",
            details: [
                "Color : Light Wash Blue",
                "Fabric : Denim (Cotton Blend)",
                "Fit : High-Waist, Palazzo",
                "Closure : Zipper and Button",
                "Features : Wide-Leg, Pleated Design",
            ]
        },
        {
            id: 28,
            shortTitle: "Fringed Two-Tone...",
            title: "Fringed Two-Tone High Waisted Jeans",
            price: "2,499",
            image: "images/tops/jeans9.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.5,
            review: "(based on 900 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false }
            ],
            description: "Trendy Fringed Two-Tone High Waisted Jeans featuring a unique design with frayed edges for an edgy look.",
            details: [
                "Color : Light Blue and Dark Blue(Two - Tone)",
                "Fabric : Denim(Cotton Blend)",
                "Fit : High - Waist, Straight - Leg",
                "Closure : Zipper and Button",
                "Features : Fringed Hem, Two - Tone Design",
            ]
        },
        {
            id: 29,
            shortTitle: "High Waist Ripped...",
            title: "High Waist Ripped Wide Leg Jeans",
            price: "1,800",
            image: "images/tops/jeans10.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Bottom Wear",
            rating: 4.6,
            review: "(based on 950 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true }
            ],
            description: "Trendy High Waist Ripped Wide Leg Jeans with a relaxed fit and distressed details for an edgy, street-style look.",
            details: [
                "Color : Light Blue",
                "Fabric : Cotton Blend Denim",
                "Fit : High-Waist, Wide-Leg",
                "Closure : Zipper and Button",
                "Features : Ripped Details, Frayed Hem",
            ]
        },
        {
            id: 30,
            shortTitle: "Lehenga choli...",
            title: "Lehenga choli for women stylish latest party wear",
            price: "6,999",
            image: "images/lehangas/lehanga1.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.8,
            review: "(based on 1,250 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false }
            ],
            description: "Elegant Lehenga Choli with intricate embroidery, perfect for parties and special occasions, designed for a stunning, traditional look.",
            details: [
                "Color : Red with Gold Embroidery",
                "Fabric : Silk Blend",
                "Fit : A - line Lehenga with Fitted Choli",
                "Embroidery : Zari and Sequin Work",
                "Closure : Zipper at the back, Tie- Up at the Waist",
                "Features : Floral Embroidery, Pleated Lehenga",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 31,
            shortTitle: "Dark green mirror...",
            title: "Dark green mirror work lehenga choli for women stylish",
            price: "8,499",
            image: "images/lehangas/lehanga2.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.9,
            review: "(based on 890 reviews)",
            sizes: [
                { "label": "L", "available": false },
                { "label": "XS", "available": true },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": true },
                { "label": "3XL", "available": true }
            ],
            description: "A stunning dark green lehenga choli adorned with mirror work, ideal for weddings and festive celebrations, combining elegance with traditional craftsmanship.",
            details: [
                "Color : Dark Green",
                "Fabric : Georgette",
                "Fit : Flared Lehenga with Crop Choli",
                "Work : Mirror Work and Thread Embroidery",
                "Closure : Side Zip and Drawstring for Lehenga",
                "Features : Heavy Mirror Detailing, Full Flair, Scalloped Dupatta",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 32,
            shortTitle: "Georgette Lehenga choli...",
            title: "Georgette Lehenga choli",
            price: "5,299",
            image: "images/lehangas/lehanga3.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.5,
            review: "(based on 1,050 reviews)",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true }
            ],
            description: "A lightweight and stylish Georgette lehenga choli, perfect for weddings, parties, and festive occasions with its elegant design and comfortable fabric.",
            details: [
                "Color : Available in multiple colors(Maroon, Peach, Navy Blue)",
                "Fabric : Georgette",
                "Fit : Flared Lehenga with Cropped Choli",
                "Work : Resham Embroidery and Sequins Detailing",
                "Closure : Drawstring for Lehenga",
                "Features : Lightweight, Flowing Flair, Comes with Dupatta",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 33,
            shortTitle: "multi-color lehanga...",
            title: "multi-color lehanga",
            price: "6,499",
            image: "images/lehangas/lehanga4.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.7,
            review: "(based on 890 reviews)",
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": true },
                { "label": "L", "available": false },
                { "label": "XS", "available": false },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": true },
            ],
            description: "A vibrant multi-color lehenga choli with exquisite embroidery and a flowing silhouette, ideal for festive celebrations, weddings, and parties.",
            details: [
                "Color : Multi - color(Combination of Red, Yellow, Green, and Pink)",
                "Fabric : Satin Silk",
                "Fit : Flared Lehenga with Cropped Choli",
                "Work : Thread Embroidery, Mirror Work, and Sequins",
                "Closure : Side Zip for Lehenga, Back Hook for Choli",
                "Features : Comes with a Net Dupatta with Embroidered Border",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 34,
            shortTitle: "Mirella Bridal Peach...",
            title: "Mirella Bridal Peach Pink Raw Silk Lehenga Set",
            price: "2,999",
            image: "images/lehangas/lehanga5.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.9,
            sizes: [
                { "label": "S", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true }
            ],
            description: "A stunning peach-pink bridal lehenga with intricate embroidery, perfect for special occasions.",
            details: [
                "Color : Peach Pink",
                "Fabric : Raw Silk",
                "Work : Zari Embroidery and Sequins",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 35,
            shortTitle: "Nitika Gujral Blue...",
            title: "Nitika Gujral Blue Tafetta Lehenga Set",
            price: "4,499",
            image: "images/lehangas/lehanga6.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.8,
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": false }
            ],
            description: "Elegant blue taffeta lehenga with delicate embroidery, a classy choice for weddings and festive occasions.",
            details: [
                "Color : Royal Blue",
                "Fabric : Taffeta Silk",
                "Work : Hand Embroidered with Resham",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 36,
            shortTitle: "VISCOS VELVET Lehenga...",
            title: "VISCOS VELVET Lehenga choli",
            price: "6,999",
            image: "images/lehangas/lehanga7.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.5,
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false }
            ],
            description: "Luxurious viscose velvet lehenga choli with intricate embroidery, perfect for weddings and grand events.",
            details: [
                "Color : Deep Maroon",
                "Fabric : Viscose Velvet",
                "Work : Zari and Stone Embroidery",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 37,
            shortTitle: "Ruby red embellished...",
            title: "Ruby red embellished lehenga set",
            price: "1,499",
            image: "images/lehangas/lehanga8.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.6,
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": false }
            ],
            description: "Stunning ruby red lehenga with delicate embellishments, ideal for festive and party wear.",
            details: [
                "Color : Ruby Red",
                "Fabric : Georgette",
                "Work : Sequins, Zari, and Mirror Work",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 38,
            shortTitle: "Pure kanchipuram silk...",
            title: "Pure kanchipuram silk Half saree",
            price: "8,999",
            image: "images/lehangas/lehanga9.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.8,
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": false },
                { "label": "XXL", "available": false }
            ],
            description: "Graceful half saree in pure Kanchipuram silk with intricate zari weaves, perfect for traditional occasions.",
            details: [
                "Color : Maroon and Gold",
                "Fabric : Pure Kanchipuram Silk",
                "Work : Zari Weaving",
                "Stitched Type : Semi - Stitched",
            ]
        },
        {
            id: 39,
            shortTitle: "half saree lehanga...",
            title: "half saree lehanga choli",
            price: "4,499",
            image: "images/lehangas/lehanga10.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.5,
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": false }
            ],
            description: "Elegant pink half saree lehenga choli featuring delicate embroidery and a graceful drape, ideal for weddings and festive occasions.",
            details: [
                "Color : Pink with Gold Accents",
                "Fabric : Net and Silk Blend",
                "Work : Embroidery and Sequin Detailing",
                "Stitched Type : Semi-Stitched",
            ]
        },
        {
            id: 40,
            shortTitle: "Embroidered Rayon A Line...",
            title: "Embroidered Rayon A Line Kurta in Dark Green",
            price: "1,299",
            image: "images/lehangas/kurti1.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.4,
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": true }
            ],
            description: "Sophisticated dark green A-line kurta in soft rayon with intricate embroidery, perfect for casual or festive occasions.",
            details: [
                "Color : Dark Green",
                "Fabric : Rayon",
                "Work : Thread Embroidery",
                "Style : A - Line with 3 / 4th Sleeves",
                "Length : Calf Length",
            ]
        },
        {
            id: 41,
            shortTitle: "Buy Kaveri Green...",
            title: "Buy Kaveri Green Linen Kurta And Pant Set",
            price: "699",
            image: "images/lehangas/kurti2.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.5,
            review: "based on 85 reviews",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": false },
                { "label": "XXXL", "available": false }
            ],
            description: "An elegant green linen kurta paired with matching pants, designed for comfort and a sophisticated look. ",
            details: [
                "Fabric : Premium Linen",
                "Kurta Design : Straight cut, round neck, 3 / 4th sleeves",
                "Pant Design : Tapered fit with elasticized waistband",
                "Color : Rich green",
                "Style : Minimalist and versatile for day - to - night wear",
                "Care Instructions : Hand wash with mild detergent, dry in shade",
            ]
        },
        {
            id: 44,
            shortTitle: "Kalamkari Cotton Slip...",
            title: "Kalamkari Cotton Slip",
            price: "950",
            image: "images/lehangas/kurti5.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.3,
            review: "based on 120 reviews",
            sizes: [
                { "label": "S", "available": true },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XL", "available": false }
            ],
            description: "A beautiful slip crafted from soft cotton, adorned with traditional Kalamkari prints, perfect for layering or wearing as a standalone piece.",
            details: [
                "Fabric : Pure Cotton",
                "Design : Kalamkari hand block print, sleeveless, straight hem",
                "Color : Multicolor",
                "Style : Casual, ideal for layering under kurtas or pairing with skirts",
                "Care Instructions : Gentle machine wash, use mild detergent, do not bleach",
            ]
        },
        {
            id: 45,
            shortTitle: "Rayon Kurta Set...",
            title: "Rayon Kurta Set in Black",
            price: "550",
            image: "images/lehangas/kurti6.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.5,
            review: "based on 200 reviews",
            sizes: [
                { "label": "M", "available": false },
                { "label": "L", "available": true },
                { "label": "XS", "available": false },
                { "label": "XXL", "available": true }
            ],
            description: "An elegant black rayon kurta set featuring intricate details and a comfortable fit, ideal for casual and festive occasions.",
            details: [
                "Fabric : Rayon",
                "Color : Black",
                "Set Includes : Kurta and matching pants",
                "Design : Round neckline, three - quarter sleeves, side slits, and subtle embroidery",
                "Occasion : Casual, festive wear",
                "Care Instructions : Hand wash or machine wash with mild detergent",
            ]
        },
        {
            id: 48,
            shortTitle: "silk kurti...",
            title: "silk kurti",
            price: "450",
            image: "images/lehangas/kurti9.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.4,
            review: "based on 180 reviews",
            sizes: [
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true },
                { "label": "XL", "available": true }
            ],
            description: "A luxurious silk kurti with an elegant design, perfect for festive occasions and formal events.",
            details: [
                "Fabric : Pure Silk",
                "Color : Available in Maroon, Green, and Blue",
                "Design : Round neckline with three- quarter sleeves, and a flared hemline",
                "Occasion : Party wear, festive celebrations",
                "Care Instructions : Dry clean only",
            ]
        },
        {
            id: 49,
            shortTitle: "stylish cotton casual...",
            title: "stylish cotton casual",
            price: "600",
            image: "images/lehangas/kurti10.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Lehangas and Kurtis",
            rating: 4.2,
            review: "based on 95 reviews",
            sizes: [
                { "label": "S", "available": false },
                { "label": "M", "available": true },
                { "label": "L", "available": true },
                { "label": "XS", "available": true },
                { "label": "XL", "available": true },
                { "label": "XXL", "available": true }
            ],
            description: "A trendy cotton kurti designed for everyday wear, combining comfort with effortless style.",
            details: [
                "Fabric : 100 % Cotton",
                "Color : Light Blue with white polka dots",
                "Design : Mandarin collar, button- down front",
                "Occasion : Casual outings, office wear, or relaxed gatherings",
                "Care Instructions : Machine wash, gentle cycle",
            ]
        },
        {
            id: 51,
            shortTitle: "Custom Stiched Sequence...",
            title: "Custom Stiched Sequence Fabric Saree Blouse Petticoat for Women and Girls Party Wear",
            price: "780",
            image: "images/sarees/saree2.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Sarees",
            rating: 4.5,
            review: "based on 120 reviews",
            description: "This set adds the perfect finishing touch to any saree, making you the center of attention at your next party or festive event.",
            details: [
                "Fabric : High - quality sequin fabric",
                "Blouse Design : Custom stitched designed to enhance the saree's appearance",
                "Color : Red, Blue, Black",
                "Occasion : Weddings, Parties, Festive Celebrations",
                "Size : Custom sizes available on request",
                "Care : Dry clean only to maintain the sequins' sparkle",
            ]
        },
        {
            id: 53,
            shortTitle: "Embroidered Georgette Silk...",
            title: "Embroidered Georgette Silk Saree in Purple",
            price: "1,050",
            image: "images/sarees/saree4.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Sarees",
            rating: 5,
            review: "based on 85 reviews",
            description: "This saree is the perfect choice for those who want to stand out with elegance and sophistication, designed to make you feel special on any occasion.",
            details: [
                "Fabric : Georgette Silk",
                "Embroidery : Intricate floral and traditional embroidery work along the borders and pallu",
                "Color : Rich Purple",
                "Occasion : Weddings, Festivals, Formal Parties",
                "Saree Length : 5.5 meters",
                "Blouse : Comes with a matching blouse piece",
                "Care Instructions : Dry clean only to preserve the fabric and embroidery",
                "Weight : Light to medium weight, ideal for draping",
            ]
        },
        {
            id: 54,
            shortTitle: "Embroidered Satin Georgette...",
            title: "Embroidered Satin Georgette Saree in Fuchsia",
            price: "990",
            image: "images/sarees/saree5.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Sarees",
            rating: 4.8,
            review: "based on 102 reviews",
            description: "This saree is perfect for making a bold fashion statement while exuding grace and elegance, ideal for making you the center of attention at any special event.",
            details: [
                "Fabric : Satin Georgette",
                "Embroidery : Intricate floral and zari embroidery on the borders and pallu",
                "Color : Vibrant Fuchsia",
                "Occasion : Weddings, Festive Celebrations, Parties",
                "Saree Length : 5.5 meters",
                "Blouse : Comes with a matching blouse piece",
                "Weight : Medium weight, easy to drape",
            ]
        },
        {
            id: 56,
            shortTitle: "Gorgeous and beautiful...",
            title: "Gorgeous and beautiful saree design",
            price: "2,150",
            image: "images/sarees/saree7.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Sarees",
            rating: 4.8,
            description: "A breathtaking saree that combines intricate craftsmanship with elegance, featuring delicate embroidery and a stunning design perfect for any festive or formal occasion.",
            details: [
                "Fabric : Luxurious Satin, Silk, or Georgette",
                "Color : Vibrant hues or elegant pastel shades",
                "Occasion : Weddings, Festivals, Parties, Celebrations",
                "Saree Length : 5.5 meters",
                "Blouse : Matching blouse piece included, with customizable designs",
                "Care Instructions : Dry clean recommended to maintain fabric and embroidery",
                "Weight : Light to Medium weight, comfortable to wear",
            ]
        },
        {
            id: 58,
            shortTitle: "Silk Saree in Bottle...",
            title: "Silk Saree in Bottle Green",
            price: "1,200",
            image: "images/sarees/saree9.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Sarees",
            rating: 4.6,
            description: "A rich and luxurious bottle green silk saree with traditional charm, perfect for elegant occasions like weddings, receptions, and festivals.",
            details: [
                "Fabric : Premium Silk",
                "Color : Bottle Green",
                "Occasion : Weddings, Festivals, Formal events",
                "Saree Length : 5.5 meters",
                "Blouse : Matching blouse piece included, can be customized",
                "Care : Dry clean only to preserve the silk fabric",
            ]
        },
        {
            id: 60,
            shortTitle: "Amozae Women's Ankel...",
            title: "Amozae Women's Ankel Boots",
            price: "1,500",
            image: "images/footwear/shoe1.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.5,
            review: "based on 420 reviews",
            sizes: [
                { "label": "5", "available": true },
                { "label": "6", "available": true },
                { "label": "7", "available": true },
                { "label": "8", "available": true },
                { "label": "9", "available": false },
                { "label": "10", "available": false }
            ],
            description: "Trendy and versatile ankle boots designed for comfort and style, perfect for everyday wear or special occasions.",
            details: [
                "Material : Premium synthetic leather",
                "Design : Sleek and modern with minimalistic detailing",
                "Closure : Side zipper for easy wear",
                "Heel Type : Block heel",
                "Heel Height : 2.5 inches",
                "Color Options : Black, Brown, Beige",
                "Toe Shape : Almond",
            ]
        },
        {
            id: 61,
            shortTitle: "Fashionable winter shoes...",
            title: "Fashionable winter shoes",
            price: "2000",
            image: "images/footwear/shoe2.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.3,
            review: "based on 320 reviews",
            sizes: [
                { "label": "5", "available": false },
                { "label": "6", "available": true },
                { "label": "7", "available": true },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": false }
            ],
            description: "Cozy and stylish winter shoes designed to keep your feet warm and fashionable during the chilly months.",
            details: [
                "Material : Faux suede with plush lining",
                "Design : Ankle - length with a trendy lace- up style",
                "Sole : Anti - slip rubber sole for added grip",
                "Colors : Available in Black, Grey, and Brown",
                "Heel Type : Flat with slight elevation for comfort",
            ]
        },
        {
            id: 62,
            shortTitle: "Demonia DAMNED-225...",
            title: "Demonia DAMNED-225 White Flatform Boots",
            price: "1,350",
            image: "images/footwear/shoe3.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.6,
            review: "based on 410 reviews",
            sizes: [
                { "label": "5", "available": true },
                { "label": "6", "available": true },
                { "label": "7", "available": false },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": false }
            ],
            description: "Turn heads and elevate your style with these iconic flatform boots, ideal for alternative fashion lovers.",
            details: [
                "Material : Faux leather",
                "Closure : Lace - up with side zipper for easy wear",
                "Heel Type : Flatform(3 - inch platform height)",
                "Color : White with black detailing",
                "Design Features : Metal buckle straps, reinforced stitching, and a rugged sole",
            ]
        },
        {
            id: 63,
            shortTitle: "White Gothic Platform...",
            title: "White Gothic Platform Ankle",
            price: "3,200",
            image: "images/footwear/shoe4.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.4,
            review: "based on 278 reviews",
            sizes: [
                { "label": "5", "available": false },
                { "label": "6", "available": true },
                { "label": "7", "available": true },
                { "label": "8", "available": true },
                { "label": "9", "available": false },
                { "label": "10", "available": true }
            ],
            description: "Sleek and stylish ankle boots with a gothic flair, featuring a bold platform sole and striking white finish. Perfect for alternative and statement looks.",
            details: [
                "Material : Synthetic leather",
                "Closure : Side zipper and lace - up",
                "Heel Type : Platform(4 - inch height)",
                "Color : White with metallic accents",
                "Design Features : Chunky sole, rivet embellishments, and gothic- inspired details",
            ]
        },
        {
            id: 64,
            shortTitle: "Amozae New Autumn...",
            title: "Amozae New Autumn Sneakers Woman Vulcanized Shoes",
            price: "2,700",
            image: "images/footwear/shoe5.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.5,
            review: "based on 143 reviews",
            sizes: [
                { "label": "4", "available": false },
                { "label": "5", "available": true },
                { "label": "6", "available": true },
                { "label": "7", "available": true },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": false }
            ],
            description: "Casual and trendy vulcanized sneakers designed for all-day comfort and style, perfect for autumn outings.",
            details: [
                "Material : Canvas upper with a rubber sole",
                "Closure : Lace - up",
                "Style : Lightweight and breathable",
                "Color Options : White, Black, Beige",
                "Design Features : Minimalist design with reinforced toe cap and non- slip sole",
            ]
        },
        {
            id: 65,
            shortTitle: "Cute Kuromi hand-painted...",
            title: "Cute Kuromi hand-painted sneakers",
            price: "1,900",
            image: "images/footwear/shoe6.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.8,
            review: "based on 97 reviews",
            sizes: [
                { "label": "5", "available": false },
                { "label": "6", "available": false },
                { "label": "7", "available": true },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": false }
            ],
            description: "Adorable hand-painted sneakers featuring the mischievous and stylish Kuromi, perfect for anime and kawaii fashion lovers.",
            details: [
                "Material : Canvas upper, rubber sole",
                "Design : Hand - painted Kuromi character on a white canvas base",
                "Style : Low - top lace - up sneakers with a playful artistic touch",
                "Color Options : White base with black and pink accents",
                "Customization : Unique hand- painted design; slight variations may occur",
                "Durability : Anti - slip sole and reinforced stitching",
            ]
        },
        {
            id: 66,
            shortTitle: "Fashion Womens Punk...",
            title: "Fashion Womens Punk Gothic Shoes Wedge Heels Platform Zipper Lace Up Ankle Boots",
            price: "2,300",
            image: "images/footwear/shoe7.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.5,
            review: "based on 112 reviews)",
            sizes: [
                { "label": "5", "available": false },
                { "label": "6", "available": false },
                { "label": "7", "available": false },
                { "label": "9", "available": true },
                { "label": "10", "available": true },
                { "label": "11", "available": false }
            ],
            description: "These stylish punk gothic ankle boots feature a bold wedge heel, platform sole, and lace-up design, with a zipper for easy wear.",
            details: [
                "Material : Synthetic leather upper, rubber platform sole",
                "Heel Type : Wedge heel",
                "Closure : Lace - up front with side zipper for convenience",
                "Style : Ankle - high boots with a platform sole and Gothic flair",
                "Heel Height : 3.5 inches(approx.)",
                "Platform Height : 1.5 inches(approx.)",
            ]
        },
        {
            id: 67,
            shortTitle: "High Platform Cut...",
            title: "High Platform Cut Out Hasp Lace High Chunky Heels Short Martin Boots",
            price: "1,250",
            image: "images/footwear/shoe8.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.2,
            review: "based on 90 reviews",
            sizes: [
                { "label": "5", "available": false },
                { "label": "6", "available": false },
                { "label": "7", "available": false },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": true },
                { "label": "11", "available": false }
            ],
            description: "These bold, statement-making boots are perfect for those who want to add a touch of edginess to their style while staying comfortable throughout the day.",
            details: [
                "Material : PU leather upper, rubber sole",
                "Heel Type : Chunky high heel",
                "Closure : Lace - up front with adjustable hasp buckle",
                "Style : Short Martin boots with chunky heels and edgy details",
                "Color Options : Black, Brown, White",
                "Toe Shape : Round toe",
                "Occasion : Casual, parties, daily wear, fashion events",
            ]
        },







        {
            id: 75,
            shortTitle: "EMERY ROSE Letter...",
            title: "EMERY ROSE Letter Detail Ankle Strap Sandals",
            price: "1,200",
            image: "images/footwear/flat6.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.5,
            review: "based on 120 reviews",
            sizes: [
                { "label": "5", "available": true },
                { "label": "6", "available": false },
                { "label": "7", "available": false },
                { "label": "8", "available": false },
                { "label": "9", "available": true },
                { "label": "10", "available": false }
            ],
            description: "Step up your summer style with these trendy ankle strap sandals featuring bold letter detailing.",
            details: [
                "Material : Synthetic leather upper, rubber sole",
                "Heel Type : Flat",
                "Closure : Ankle strap with buckle for adjustable fit",
                "Style : Open - toe sandals with ankle strap",
                "Color Options : Black, White, Tan",
                "Comfort : Cushioned insole for added comfort",
            ]
        },
        {
            id: 77,
            shortTitle: "Crystal-Encrusted Palm...",
            title: "Crystal-Encrusted Palm Tree 'Venice Beach' Sandals",
            price: "2,045",
            image: "images/footwear/flat8.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 5,
            review: "based on 150 reviews)",
            sizes: [
                { "label": "6", "available": true },
                { "label": "7", "available": true },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": false },
                { "label": "12", "available": false }
            ],
            description: "Elevate your beach style with these stunning 'Venice Beach' sandals, featuring a crystal-encrusted palm tree design.",
            details: [
                "Material : High - quality synthetic upper, rubber sole",
                "Heel Type : Flat",
                "Closure : Slip - on design for easy wear",
                "Design : Crystal - encrusted palm tree on the strap for a bold and fashionable look",
                "Style : Open - toe sandals with a chic tropical theme",
                "Color Options : Gold, Silver, Rose Gold",
            ]
        },
        {
            id: 82,
            shortTitle: "Wedding Bow High...",
            title: "Wedding Bow High Heels Stiletto Heels",
            price: "750",
            image: "images/footwear/heel4.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.8,
            review: "based on 120 reviews",
            sizes: [
                { "label": "5", "available": false },
                { "label": "6", "available": true },
                { "label": "7", "available": false },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": false }
            ],
            description: "Elegant stiletto heels with a charming bow detail, perfect for weddings and formal events, offering both style and comfort.",
            details: [
                "Material : Satin",
                "Color : White",
                "Heel Type : Stiletto",
                "Heel Height : 4.5 inches",
                "Design : Bow on the toe, open - toe design",
                "Occasion : Wedding, evening parties, formal events",
                "Care Instructions : Wipe clean with a damp cloth",
            ]
        },
        {
            id: 84,
            shortTitle: "Glitter Panel Stiletto...",
            title: "Glitter Panel Stiletto Heeled Ankle Strap Pumps",
            price: "550",
            image: "images/footwear/heel6.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.7,
            review: "based on 85 reviews",
            sizes: [
                { "label": "5", "available": false },
                { "label": "6", "available": true },
                { "label": "7", "available": true },
                { "label": "8", "available": true },
                { "label": "9", "available": false },
                { "label": "10", "available": false }
            ],
            description: "Chic and elegant high heels with signature Rockstud detailing, perfect for adding a luxe touch to your wardrobe.",
            details: [
                "Material : Leather",
                "Color : Beige",
                "Heel Type : Stiletto",
                "Heel Height : 4 inches",
                "Design : Rockstud straps, open - toe",
                "Occasion : Evening, formal, cocktail parties",
                "Care Instructions : Clean with a soft cloth, store in dust bags to maintain quality",
            ]
        },
        {
            id: 86,
            shortTitle: "Snakeskin Pattern Chunky...",
            title: "Snakeskin Pattern Chunky Heeled Ankle Strap Sandals",
            price: "850",
            image: "images/footwear/heel8.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.3,
            review: "based on 85 reviews",
            sizes: [
                { "label": "5", "available": false },
                { "label": "6", "available": true },
                { "label": "7", "available": false },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": false }
            ],
            description: "Elevate your style with these chic snakeskin pattern chunky heeled ankle strap sandals.",
            details: [
                "Material : Faux leather with snakeskin pattern",
                "Color : Beige and brown",
                "Heel Type : Chunky",
                "Design : Ankle strap with buckle, snakeskin pattern",
                "Occasion : Casual, evening, party",
                "Care Instructions : Wipe with a damp cloth for cleaning, store in a cool, dry place",
            ]
        },
        {
            id: 88,
            shortTitle: "Suede Buckled Cutout...",
            title: "Suede Buckled Cutout Stiletto Heels",
            price: "580",
            image: "images/footwear/heel10.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Footwear",
            rating: 4.6,
            review: "based on 150 reviews",
            sizes: [
                { "label": "5", "available": true },
                { "label": "6", "available": true },
                { "label": "7", "available": false },
                { "label": "8", "available": true },
                { "label": "9", "available": true },
                { "label": "10", "available": false }
            ],
            description: "A sophisticated and stylish pair of suede stiletto heels featuring a buckled cutout design.",
            details: [
                "Material : Suede",
                "Color : Black",
                "Heel Type : Stiletto",
                "Heel Height : 4.5 inches",
                "Design : Cutout design with buckle strap",
                "Occasion : Evening, Party, Cocktail",
                "Care Instructions : Gently clean with a suede brush, store in a dust bag",
            ]
        },
        {
            id: 90,
            shortTitle: "Quilted Bucket Bag...",
            title: "Quilted Bucket Bag Small Twist Lock Green",
            price: "1,950",
            image: "images/handbags/bag1.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Handbags",
            rating: 4.7,
            review: "based on 560 reviews",
            sizes: [
                { "label": "One size", "available": true }
            ],
            description: "Stylish and functional, this bag complements both casual and formal outfits!",
            details: [
                "Material : PU Leather",
                "Design : Quilted pattern with a structured bucket shape",
                "Closure : Elegant twist- lock mechanism",
                "Color : Green",
            ]
        },
        {
            id: 91,
            shortTitle: "2pcs Pattern Bag Set...",
            title: "2pcs Pattern Bag Set, Women's Tassel Decor Crossbody Bag, Fashion Handbag With Clutch Bag",
            price: "2000",
            image: "images/handbags/bag2.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Handbags",
            rating: 4.6,
            review: "based on 950 reviews",
            sizes: [{ "label": "One size", "available": true }],
            description: "Ideal for work, casual outings, or formal occasions!",
            details: [
                "Material : PU Leather",
                "Closure : Zipper for both bags",
                "Design : All - over patterned design with tassel embellishments",
                "Strap Type : Adjustable shoulder strap for the main bag",
                "Care Instructions : Wipe clean with a soft, damp cloth.Avoid harsh chemicals",
            ]
        },
        {
            id: 92,
            shortTitle: "Fashion Sequins Handbags...",
            title: "Fashion Sequins Handbags Women Shoulder Bags For Party Wedding Bridal Bag",
            price: "1,799",
            image: "images/handbags/bag3.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Handbags",
            rating: 4.5,
            review: "(based on 200 reviews)",
            sizes: [{ "label": "One size", "available": true }],
            description: "Glamorous and sparkling sequins handbag designed for parties, weddings, and bridal occasions, adding an elegant touch to your outfit.",
            details: [
                "Material : High - quality sequins and durable fabric",
                "Strap Type : Detachable shoulder strap",
                "Closure Type : Snap button or zipper(depending on design)",
                "Compartments : Single main compartment with inner pockets for small essentials",
                "Dimensions : 25cm x 15cm x 5cm(approx.)",
                "Color Options : Silver, Gold, Black, Red",
                "Style : Evening / Occasion wear",
            ]
        },
        {
            id: 93,
            shortTitle: "Women Composite Tassel...",
            title: "Women Composite Tassel Bag Luxury Leather Purse Handbags Famous Brands",
            price: "1,799",
            image: "images/handbags/bag4.png",
            alt: "Product",
            buy: "Buy Now",
            cart: "Add To Cart",
            category: "Handbags",
            rating: 4.6,
            sizes: [{ "label": "One size", "available": true }],
            description: "Elegant luxury leather handbag with a tassel design, spacious compartments, and durable handles for a stylish everyday look.",
            details: [
                "Color : Black, Brown, Beige",
                "Material : Luxury PU Leather",
                "Features : Tassel design, spacious compartments, and durable handles",
                "Closure : Zipper",
                "Includes : Composite bag (main handbag + additional pouch)",
                "Style: Handbag",
            ]
        }
    ]

};

export default collectionsdata;

